# Importing libraries

In [13]:
import pandas as pd
import numpy as np
import pickle
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,r2_score
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv('./IceCreamData.csv')

In [3]:
df.head()

Temperature     Revenue
0    24.566884  534.799028
1    26.005191  625.190122
2    27.790554  660.632289
3    20.595335  487.706960
4    11.503498  316.240194

In [4]:
df.isnull().sum()

Temperature    0
Revenue        0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Temperature  500 non-null    float64
 1   Revenue      500 non-null    float64
dtypes: float64(2)
memory usage: 7.9 KB


In [6]:
x = df['Temperature']
y = df['Revenue']

In [9]:
x_tarin,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [11]:
len(x_test)

100

In [14]:
model = LinearRegression()

In [18]:
np.array([x_tarin]).reshape(-1,1)

array([[13.30179635],
       [16.30255473],
       [16.19129752],
       [20.59533505],
       [16.70385182],
       [28.70127646],
       [13.33060576],
       [17.51707397],
       [ 9.3093456 ],
       [22.18951589],
       [29.3050392 ],
       [31.41262876],
       [26.87495294],
       [23.40725697],
       [21.71200518],
       [16.14582413],
       [41.92444647],
       [ 8.99176011],
       [10.4471261 ],
       [26.4560508 ],
       [13.36431317],
       [24.62861149],
       [27.18851714],
       [16.40602096],
       [29.50819457],
       [35.62892497],
       [21.12912561],
       [14.35251388],
       [28.72991474],
       [26.36052065],
       [21.14404693],
       [26.36974685],
       [ 7.56112494],
       [ 3.98652317],
       [19.72133149],
       [ 3.66466958],
       [16.30012497],
       [22.52674945],
       [17.57423462],
       [29.7185162 ],
       [23.82492237],
       [12.20968364],
       [18.15921677],
       [21.61064376],
       [36.56911506],
       [12

In [19]:
model.fit(np.array([x_tarin]).reshape(-1,1),y_train)

LinearRegression()

In [22]:
y_pred = model.predict(np.array([x_test]).reshape(-1,1))

In [23]:
y_pred

array([805.47622578, 600.61805178, 148.06534484, 422.97189266,
       519.54733485, 683.20313409, 548.44942809, 697.99896474,
       620.99897316, 472.80517386, 724.03870672, 368.05387678,
       456.16165369, 681.82693986, 451.48351121, 435.3224279 ,
       832.2184686 , 671.20109068, 545.25828997, 502.47257946,
       184.09543206, 437.76344713, 443.93292839, 583.14486695,
       651.62366347, 768.64486737, 409.8898744 , 841.34070165,
       798.21311893, 629.75544225, 898.0096306 , 423.64944017,
       363.62813455, 441.18911895, 650.85307695, 746.55740885,
       468.01820515, 710.32516812, 664.54960923, 483.46666587,
       604.93894313, 307.19671946, 775.467009  , 909.60618143,
       500.83705829, 422.50846086, 310.8861068 , 465.18053624,
       472.9212272 , 410.76894245, 485.3882677 , 509.48676972,
       313.65530946, 701.83628352, 253.7183764 , 529.90839469,
       169.39535665, 380.05664525, 445.53525051, 731.25235818,
       189.09585323, 256.25225136, 662.18383101, 198.72

In [24]:
y_test

268    828.296077
116    572.081292
484    188.151331
103    401.433018
317    537.766112
          ...    
396    192.341996
271    651.486741
388    221.400252
136    599.364914
62     774.108081
Name: Revenue, Length: 100, dtype: float64

In [25]:
r2_score(y_test,y_pred)

0.9794730105434577

In [31]:
model.predict([[24]])

array([559.24718685])

In [32]:
with open('model.pkl','wb') as files:
    pickle.dump(model,files)